<?php

use Drupal\Core\Form\FormStateInterface;
use Drupal\paragon_gin\FormAlter;
use Drupal\paragon_gin\LibraryInfoAlter;
use Drupal\paragon_gin\Preprocess;
use Drupal\paragon_gin\ThemeRegistryAlter;

/**
 * Implements hook_library_info_alter.
 */
function paragon_gin_library_info_alter(&$libraries, $extension) {
  \Drupal::service('class_resolver')
    ->getInstanceFromDefinition(LibraryInfoAlter::class)
    ->libraryInfoAlter($libraries, $extension);
}

/**
 * Implements hook_theme_registry_alter.
 */
function paragon_gin_theme_registry_alter(&$theme_registry) {
  \Drupal::service('class_resolver')
    ->getInstanceFromDefinition(ThemeRegistryAlter::class)
    ->themeRegistryAlter($theme_registry);
}

/**
 * Implements theme_preprocess_toolbar.
 */
function paragon_gin_preprocess_toolbar(&$variables) {
  \Drupal::service('class_resolver')
    ->getInstanceFromDefinition(Preprocess::class)
    ->toolbar($variables);
}

/**
 * Implements theme_preprocess_menu_local_task.
 */
function paragon_gin_preprocess_menu_local_task(&$variables) {
  \Drupal::service('class_resolver')
    ->getInstanceFromDefinition(Preprocess::class)
    ->menuLocalTask($variables);
}

/**
 * Implements theme_preprocess_menu_local_tasks.
 */
function paragon_gin_preprocess_menu_local_tasks(&$variables) {
  \Drupal::service('class_resolver')
    ->getInstanceFromDefinition(Preprocess::class)
    ->menuLocalTasks($variables);
}
